CREATE TABLE "news_detail_backup" (
	"news_id" BIGINT NOT NULL,
	"news_body" TEXT NULL DEFAULT NULL,
	"insert_time" DATETIME NULL DEFAULT NULL,
	"update_time" DATETIME NULL DEFAULT NULL,
	"source_name" NVARCHAR(50) NULL DEFAULT NULL,
	"news_author" NVARCHAR(500) NULL DEFAULT NULL,
	"news_url" VARCHAR(500) NULL DEFAULT NULL,
	"news_title" NVARCHAR(300) NULL DEFAULT NULL,
	"news_fetch_time" DATETIME2(7) NULL DEFAULT NULL,
	"news_site_name" NVARCHAR(50) NULL DEFAULT NULL,
	"news_publish_time" DATETIME2(7) NULL DEFAULT NULL,
	"news_comments_num" INT NULL DEFAULT NULL,
	"hashValue" VARCHAR(200) NULL DEFAULT NULL,
	"has_summary" INT NULL DEFAULT NULL,
	"isActive" INT NULL DEFAULT '1',
	"source_type" VARCHAR(64) NULL DEFAULT NULL,
	"news_tag" INT NULL DEFAULT '-1',
	"related_company_id" VARCHAR(500) NULL DEFAULT NULL,
	"main_related_company_id" BIGINT NULL DEFAULT NULL,
	"event_id" INT NULL DEFAULT '-1',
	"neg_pos" FLOAT(53) NULL DEFAULT NULL,
	"duplicate_num" INT NULL DEFAULT '0',
	"kpi_tag" VARCHAR(500) NULL DEFAULT NULL,
	"comments_num" INT NULL DEFAULT NULL,
	"kpi_type" INT NULL DEFAULT '-1',
	"usefull" INT NULL DEFAULT '1',
	"group_id" BIGINT NOT NULL DEFAULT '-1',
	"auto_update_time" DATETIME2(7) NOT NULL DEFAULT '',
	"page_tag" NVARCHAR(150) NULL DEFAULT NULL,
	"TMSTAMP" TIMESTAMP NOT NULL,
	PRIMARY KEY ("news_id"),
	UNIQUE INDEX "UNIQUE" ("TMSTAMP")
)
;
