-- simple update

CREATE TABLE test4 (ID BIGINT NOT NULL, TMSTAMP TIMESTAMP NOT NULL, PRIMARY KEY (ID));
INSERT INTO test4 (ID) VALUES (1);
INSERT INTO test4 (ID) VALUES (2);
INSERT INTO test4 (ID) VALUES (3);
UPDATE test4 SET Id = 10 WHERE ID = 2;
UPDATE test4 SET Id = 2 WHERE ID = 1;
UPDATE test4 SET Id = 7 WHERE ID = 10;