-- simple insertion

CREATE TABLE test1 (ID BIGINT NOT NULL, TMSTAMP TIMESTAMP NOT NULL, PRIMARY KEY (ID));
INSERT INTO test1 (ID) VALUES (1);
INSERT INTO test1 (ID) VALUES (2);
INSERT INTO test1 (ID) VALUES (3);
INSERT INTO test1 (ID) VALUES (4);
INSERT INTO test1 (ID) VALUES (5);