-- deletion followed by insertion

CREATE TABLE test5 (ID BIGINT NOT NULL, TMSTAMP TIMESTAMP NOT NULL, PRIMARY KEY (ID));
INSERT INTO test5 (ID) VALUES (1);
DELETE FROM test5 WHERE ID = 1;
INSERT INTO test5 (ID) VALUES (1);
DELETE FROM test5 WHERE ID = 1;
INSERT INTO test5 (ID) VALUES (1);
DELETE FROM test5 WHERE ID = 1;
INSERT INTO test5 (ID) VALUES (1);
DELETE FROM test5 WHERE ID = 1;
INSERT INTO test5 (ID) VALUES (2);
DELETE FROM test5 WHERE ID = 2;
INSERT INTO test5 (ID) VALUES (1);
DELETE FROM test5 WHERE ID = 1;
INSERT INTO test5 (ID) VALUES (2);
DELETE FROM test5 WHERE ID = 2;
INSERT INTO test5 (ID) VALUES (1);
DELETE FROM test5 WHERE ID = 1;
INSERT INTO test5 (ID) VALUES (1);