// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IncrementMessage.proto

package com.datayes.heterDataTransfer.scanner;

public final class IncrementMessageProtos {
  private IncrementMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InsertUpdateContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InsertUpdateContent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string values = 2;</code>
     */
    com.google.protobuf.ProtocolStringList
        getValuesList();
    /**
     * <code>repeated string values = 2;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated string values = 2;</code>
     */
    java.lang.String getValues(int index);
    /**
     * <code>repeated string values = 2;</code>
     */
    com.google.protobuf.ByteString
        getValuesBytes(int index);
  }
  /**
   * Protobuf type {@code InsertUpdateContent}
   */
  public static final class InsertUpdateContent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:InsertUpdateContent)
      InsertUpdateContentOrBuilder {
    // Use InsertUpdateContent.newBuilder() to construct.
    private InsertUpdateContent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InsertUpdateContent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InsertUpdateContent defaultInstance;
    public static InsertUpdateContent getDefaultInstance() {
      return defaultInstance;
    }

    public InsertUpdateContent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InsertUpdateContent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                values_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              values_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = values_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.internal_static_InsertUpdateContent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.internal_static_InsertUpdateContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.class, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder.class);
    }

    public static com.google.protobuf.Parser<InsertUpdateContent> PARSER =
        new com.google.protobuf.AbstractParser<InsertUpdateContent>() {
      public InsertUpdateContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InsertUpdateContent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InsertUpdateContent> getParserForType() {
      return PARSER;
    }

    public static final int VALUES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList values_;
    /**
     * <code>repeated string values = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public java.lang.String getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated string values = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValuesBytes(int index) {
      return values_.getByteString(index);
    }

    private void initFields() {
      values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < values_.size(); i++) {
        output.writeBytes(2, values_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(values_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InsertUpdateContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InsertUpdateContent)
        com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.internal_static_InsertUpdateContent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.internal_static_InsertUpdateContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.class, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder.class);
      }

      // Construct using com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.internal_static_InsertUpdateContent_descriptor;
      }

      public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent getDefaultInstanceForType() {
        return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.getDefaultInstance();
      }

      public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent build() {
        com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent buildPartial() {
        com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent result = new com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = values_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.values_ = values_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent) {
          return mergeFrom((com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent other) {
        if (other == com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.getDefaultInstance()) return this;
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = new com.google.protobuf.LazyStringArrayList(values_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValuesList() {
        return values_.getUnmodifiableView();
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public java.lang.String getValues(int index) {
        return values_.get(index);
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValuesBytes(int index) {
        return values_.getByteString(index);
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder setValues(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addValues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<java.lang.String> values) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder clearValues() {
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 2;</code>
       */
      public Builder addValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InsertUpdateContent)
    }

    static {
      defaultInstance = new InsertUpdateContent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:InsertUpdateContent)
  }

  public interface IncrementMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IncrementMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 0: insert; 1: update; 2: delete
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 0: insert; 1: update; 2: delete
     * </pre>
     */
    int getType();

    /**
     * <code>repeated string fields = 2;</code>
     */
    com.google.protobuf.ProtocolStringList
        getFieldsList();
    /**
     * <code>repeated string fields = 2;</code>
     */
    int getFieldsCount();
    /**
     * <code>repeated string fields = 2;</code>
     */
    java.lang.String getFields(int index);
    /**
     * <code>repeated string fields = 2;</code>
     */
    com.google.protobuf.ByteString
        getFieldsBytes(int index);

    /**
     * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
     */
    java.util.List<com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent> 
        getInsertUpdateContentsList();
    /**
     * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
     */
    com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent getInsertUpdateContents(int index);
    /**
     * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
     */
    int getInsertUpdateContentsCount();
    /**
     * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
     */
    java.util.List<? extends com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContentOrBuilder> 
        getInsertUpdateContentsOrBuilderList();
    /**
     * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
     */
    com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContentOrBuilder getInsertUpdateContentsOrBuilder(
        int index);

    /**
     * <code>repeated int64 delete_ids = 4 [packed = true];</code>
     */
    java.util.List<java.lang.Long> getDeleteIdsList();
    /**
     * <code>repeated int64 delete_ids = 4 [packed = true];</code>
     */
    int getDeleteIdsCount();
    /**
     * <code>repeated int64 delete_ids = 4 [packed = true];</code>
     */
    long getDeleteIds(int index);
  }
  /**
   * Protobuf type {@code IncrementMessage}
   */
  public static final class IncrementMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IncrementMessage)
      IncrementMessageOrBuilder {
    // Use IncrementMessage.newBuilder() to construct.
    private IncrementMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IncrementMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IncrementMessage defaultInstance;
    public static IncrementMessage getDefaultInstance() {
      return defaultInstance;
    }

    public IncrementMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IncrementMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                fields_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              fields_.add(bs);
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                insertUpdateContents_ = new java.util.ArrayList<com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent>();
                mutable_bitField0_ |= 0x00000004;
              }
              insertUpdateContents_.add(input.readMessage(com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                deleteIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              deleteIds_.add(input.readInt64());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                deleteIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                deleteIds_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          fields_ = fields_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          insertUpdateContents_ = java.util.Collections.unmodifiableList(insertUpdateContents_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          deleteIds_ = java.util.Collections.unmodifiableList(deleteIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.internal_static_IncrementMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.internal_static_IncrementMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage.class, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<IncrementMessage> PARSER =
        new com.google.protobuf.AbstractParser<IncrementMessage>() {
      public IncrementMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IncrementMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IncrementMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 0: insert; 1: update; 2: delete
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     * 0: insert; 1: update; 2: delete
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int FIELDS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList fields_;
    /**
     * <code>repeated string fields = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFieldsList() {
      return fields_;
    }
    /**
     * <code>repeated string fields = 2;</code>
     */
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <code>repeated string fields = 2;</code>
     */
    public java.lang.String getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <code>repeated string fields = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFieldsBytes(int index) {
      return fields_.getByteString(index);
    }

    public static final int INSERT_UPDATE_CONTENTS_FIELD_NUMBER = 3;
    private java.util.List<com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent> insertUpdateContents_;
    /**
     * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
     */
    public java.util.List<com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent> getInsertUpdateContentsList() {
      return insertUpdateContents_;
    }
    /**
     * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
     */
    public java.util.List<? extends com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContentOrBuilder> 
        getInsertUpdateContentsOrBuilderList() {
      return insertUpdateContents_;
    }
    /**
     * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
     */
    public int getInsertUpdateContentsCount() {
      return insertUpdateContents_.size();
    }
    /**
     * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
     */
    public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent getInsertUpdateContents(int index) {
      return insertUpdateContents_.get(index);
    }
    /**
     * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
     */
    public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContentOrBuilder getInsertUpdateContentsOrBuilder(
        int index) {
      return insertUpdateContents_.get(index);
    }

    public static final int DELETE_IDS_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Long> deleteIds_;
    /**
     * <code>repeated int64 delete_ids = 4 [packed = true];</code>
     */
    public java.util.List<java.lang.Long>
        getDeleteIdsList() {
      return deleteIds_;
    }
    /**
     * <code>repeated int64 delete_ids = 4 [packed = true];</code>
     */
    public int getDeleteIdsCount() {
      return deleteIds_.size();
    }
    /**
     * <code>repeated int64 delete_ids = 4 [packed = true];</code>
     */
    public long getDeleteIds(int index) {
      return deleteIds_.get(index);
    }
    private int deleteIdsMemoizedSerializedSize = -1;

    private void initFields() {
      type_ = 0;
      fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      insertUpdateContents_ = java.util.Collections.emptyList();
      deleteIds_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      for (int i = 0; i < fields_.size(); i++) {
        output.writeBytes(2, fields_.getByteString(i));
      }
      for (int i = 0; i < insertUpdateContents_.size(); i++) {
        output.writeMessage(3, insertUpdateContents_.get(i));
      }
      if (getDeleteIdsList().size() > 0) {
        output.writeRawVarint32(34);
        output.writeRawVarint32(deleteIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < deleteIds_.size(); i++) {
        output.writeInt64NoTag(deleteIds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < fields_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fields_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFieldsList().size();
      }
      for (int i = 0; i < insertUpdateContents_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, insertUpdateContents_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < deleteIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(deleteIds_.get(i));
        }
        size += dataSize;
        if (!getDeleteIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        deleteIdsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IncrementMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IncrementMessage)
        com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.internal_static_IncrementMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.internal_static_IncrementMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage.class, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage.Builder.class);
      }

      // Construct using com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInsertUpdateContentsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (insertUpdateContentsBuilder_ == null) {
          insertUpdateContents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          insertUpdateContentsBuilder_.clear();
        }
        deleteIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.internal_static_IncrementMessage_descriptor;
      }

      public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage getDefaultInstanceForType() {
        return com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage.getDefaultInstance();
      }

      public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage build() {
        com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage buildPartial() {
        com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage result = new com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          fields_ = fields_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.fields_ = fields_;
        if (insertUpdateContentsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            insertUpdateContents_ = java.util.Collections.unmodifiableList(insertUpdateContents_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.insertUpdateContents_ = insertUpdateContents_;
        } else {
          result.insertUpdateContents_ = insertUpdateContentsBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          deleteIds_ = java.util.Collections.unmodifiableList(deleteIds_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.deleteIds_ = deleteIds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage) {
          return mergeFrom((com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage other) {
        if (other == com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.fields_.isEmpty()) {
          if (fields_.isEmpty()) {
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFieldsIsMutable();
            fields_.addAll(other.fields_);
          }
          onChanged();
        }
        if (insertUpdateContentsBuilder_ == null) {
          if (!other.insertUpdateContents_.isEmpty()) {
            if (insertUpdateContents_.isEmpty()) {
              insertUpdateContents_ = other.insertUpdateContents_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureInsertUpdateContentsIsMutable();
              insertUpdateContents_.addAll(other.insertUpdateContents_);
            }
            onChanged();
          }
        } else {
          if (!other.insertUpdateContents_.isEmpty()) {
            if (insertUpdateContentsBuilder_.isEmpty()) {
              insertUpdateContentsBuilder_.dispose();
              insertUpdateContentsBuilder_ = null;
              insertUpdateContents_ = other.insertUpdateContents_;
              bitField0_ = (bitField0_ & ~0x00000004);
              insertUpdateContentsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInsertUpdateContentsFieldBuilder() : null;
            } else {
              insertUpdateContentsBuilder_.addAllMessages(other.insertUpdateContents_);
            }
          }
        }
        if (!other.deleteIds_.isEmpty()) {
          if (deleteIds_.isEmpty()) {
            deleteIds_ = other.deleteIds_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureDeleteIdsIsMutable();
            deleteIds_.addAll(other.deleteIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.IncrementMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 0: insert; 1: update; 2: delete
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 0: insert; 1: update; 2: delete
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 0: insert; 1: update; 2: delete
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       * 0: insert; 1: update; 2: delete
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          fields_ = new com.google.protobuf.LazyStringArrayList(fields_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string fields = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFieldsList() {
        return fields_.getUnmodifiableView();
      }
      /**
       * <code>repeated string fields = 2;</code>
       */
      public int getFieldsCount() {
        return fields_.size();
      }
      /**
       * <code>repeated string fields = 2;</code>
       */
      public java.lang.String getFields(int index) {
        return fields_.get(index);
      }
      /**
       * <code>repeated string fields = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFieldsBytes(int index) {
        return fields_.getByteString(index);
      }
      /**
       * <code>repeated string fields = 2;</code>
       */
      public Builder setFields(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 2;</code>
       */
      public Builder addFields(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 2;</code>
       */
      public Builder addAllFields(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fields_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 2;</code>
       */
      public Builder clearFields() {
        fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 2;</code>
       */
      public Builder addFieldsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent> insertUpdateContents_ =
        java.util.Collections.emptyList();
      private void ensureInsertUpdateContentsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          insertUpdateContents_ = new java.util.ArrayList<com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent>(insertUpdateContents_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContentOrBuilder> insertUpdateContentsBuilder_;

      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public java.util.List<com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent> getInsertUpdateContentsList() {
        if (insertUpdateContentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(insertUpdateContents_);
        } else {
          return insertUpdateContentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public int getInsertUpdateContentsCount() {
        if (insertUpdateContentsBuilder_ == null) {
          return insertUpdateContents_.size();
        } else {
          return insertUpdateContentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent getInsertUpdateContents(int index) {
        if (insertUpdateContentsBuilder_ == null) {
          return insertUpdateContents_.get(index);
        } else {
          return insertUpdateContentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public Builder setInsertUpdateContents(
          int index, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent value) {
        if (insertUpdateContentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInsertUpdateContentsIsMutable();
          insertUpdateContents_.set(index, value);
          onChanged();
        } else {
          insertUpdateContentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public Builder setInsertUpdateContents(
          int index, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder builderForValue) {
        if (insertUpdateContentsBuilder_ == null) {
          ensureInsertUpdateContentsIsMutable();
          insertUpdateContents_.set(index, builderForValue.build());
          onChanged();
        } else {
          insertUpdateContentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public Builder addInsertUpdateContents(com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent value) {
        if (insertUpdateContentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInsertUpdateContentsIsMutable();
          insertUpdateContents_.add(value);
          onChanged();
        } else {
          insertUpdateContentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public Builder addInsertUpdateContents(
          int index, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent value) {
        if (insertUpdateContentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInsertUpdateContentsIsMutable();
          insertUpdateContents_.add(index, value);
          onChanged();
        } else {
          insertUpdateContentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public Builder addInsertUpdateContents(
          com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder builderForValue) {
        if (insertUpdateContentsBuilder_ == null) {
          ensureInsertUpdateContentsIsMutable();
          insertUpdateContents_.add(builderForValue.build());
          onChanged();
        } else {
          insertUpdateContentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public Builder addInsertUpdateContents(
          int index, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder builderForValue) {
        if (insertUpdateContentsBuilder_ == null) {
          ensureInsertUpdateContentsIsMutable();
          insertUpdateContents_.add(index, builderForValue.build());
          onChanged();
        } else {
          insertUpdateContentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public Builder addAllInsertUpdateContents(
          java.lang.Iterable<? extends com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent> values) {
        if (insertUpdateContentsBuilder_ == null) {
          ensureInsertUpdateContentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, insertUpdateContents_);
          onChanged();
        } else {
          insertUpdateContentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public Builder clearInsertUpdateContents() {
        if (insertUpdateContentsBuilder_ == null) {
          insertUpdateContents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          insertUpdateContentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public Builder removeInsertUpdateContents(int index) {
        if (insertUpdateContentsBuilder_ == null) {
          ensureInsertUpdateContentsIsMutable();
          insertUpdateContents_.remove(index);
          onChanged();
        } else {
          insertUpdateContentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder getInsertUpdateContentsBuilder(
          int index) {
        return getInsertUpdateContentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContentOrBuilder getInsertUpdateContentsOrBuilder(
          int index) {
        if (insertUpdateContentsBuilder_ == null) {
          return insertUpdateContents_.get(index);  } else {
          return insertUpdateContentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public java.util.List<? extends com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContentOrBuilder> 
           getInsertUpdateContentsOrBuilderList() {
        if (insertUpdateContentsBuilder_ != null) {
          return insertUpdateContentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(insertUpdateContents_);
        }
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder addInsertUpdateContentsBuilder() {
        return getInsertUpdateContentsFieldBuilder().addBuilder(
            com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.getDefaultInstance());
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder addInsertUpdateContentsBuilder(
          int index) {
        return getInsertUpdateContentsFieldBuilder().addBuilder(
            index, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.getDefaultInstance());
      }
      /**
       * <code>repeated .InsertUpdateContent insert_update_contents = 3;</code>
       */
      public java.util.List<com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder> 
           getInsertUpdateContentsBuilderList() {
        return getInsertUpdateContentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContentOrBuilder> 
          getInsertUpdateContentsFieldBuilder() {
        if (insertUpdateContentsBuilder_ == null) {
          insertUpdateContentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContent.Builder, com.datayes.heterDataTransfer.scanner.IncrementMessageProtos.InsertUpdateContentOrBuilder>(
                  insertUpdateContents_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          insertUpdateContents_ = null;
        }
        return insertUpdateContentsBuilder_;
      }

      private java.util.List<java.lang.Long> deleteIds_ = java.util.Collections.emptyList();
      private void ensureDeleteIdsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          deleteIds_ = new java.util.ArrayList<java.lang.Long>(deleteIds_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int64 delete_ids = 4 [packed = true];</code>
       */
      public java.util.List<java.lang.Long>
          getDeleteIdsList() {
        return java.util.Collections.unmodifiableList(deleteIds_);
      }
      /**
       * <code>repeated int64 delete_ids = 4 [packed = true];</code>
       */
      public int getDeleteIdsCount() {
        return deleteIds_.size();
      }
      /**
       * <code>repeated int64 delete_ids = 4 [packed = true];</code>
       */
      public long getDeleteIds(int index) {
        return deleteIds_.get(index);
      }
      /**
       * <code>repeated int64 delete_ids = 4 [packed = true];</code>
       */
      public Builder setDeleteIds(
          int index, long value) {
        ensureDeleteIdsIsMutable();
        deleteIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 delete_ids = 4 [packed = true];</code>
       */
      public Builder addDeleteIds(long value) {
        ensureDeleteIdsIsMutable();
        deleteIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 delete_ids = 4 [packed = true];</code>
       */
      public Builder addAllDeleteIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureDeleteIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deleteIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 delete_ids = 4 [packed = true];</code>
       */
      public Builder clearDeleteIds() {
        deleteIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:IncrementMessage)
    }

    static {
      defaultInstance = new IncrementMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:IncrementMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InsertUpdateContent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InsertUpdateContent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IncrementMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IncrementMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026IncrementMessage.proto\"%\n\023InsertUpdate" +
      "Content\022\016\n\006values\030\002 \003(\t\"~\n\020IncrementMess" +
      "age\022\014\n\004type\030\001 \002(\005\022\016\n\006fields\030\002 \003(\t\0224\n\026ins" +
      "ert_update_contents\030\003 \003(\0132\024.InsertUpdate" +
      "Content\022\026\n\ndelete_ids\030\004 \003(\003B\002\020\001B?\n%com.d" +
      "atayes.heterDataTransfer.scannerB\026Increm" +
      "entMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_InsertUpdateContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InsertUpdateContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_InsertUpdateContent_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_IncrementMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IncrementMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IncrementMessage_descriptor,
        new java.lang.String[] { "Type", "Fields", "InsertUpdateContents", "DeleteIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
